### ISSUE TITLE
Plugin deprecation: VS Code now handles path environment.

### ISSUE THREAD

**Issue by mathiasvr** [oh-my-fish/plugin-vscode#3]
The February release of VS Code can automatically add the `code` command to the $PATH environment, making this plugin redundant.

**Comment by derekstavis** [comment]
You could add this deprecation notice to README. If you'd like, you can also PR Oh My Fish removing the plugin from database.

**Comment by bobthecow** [comment]
:+1:

**Comment by mathiasvr** [comment]
I think I will leave it as is until VS Code is not in beta anymore - just to be sure.

**Comment by mathiasvr** [comment]
Version 1.0 of VS Code has been released, and `code` can be added to the PATH through a shell command in VS Code, so I don't think anyone needs this plugin anymore.
I will PR its removal.
